os: linux
language: android
sudo: enabled
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova@7.1.0
- android list targets
- npm i
- npm install --save ./kinvey-universal-runner-1.0.0.tgz
    
before_script:
- echo no | android create avd --force -n test -t android-24 -b google_apis/armeabi-v7a
- emulator -avd test -no-window &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android
- adb devices
- cd packages/kinvey-phonegap-sdk/KinveyCordovaTestApp/ && cordova run android

after_script:
- adb logcat | grep chromium

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-google_apis-24