os: linux
language: android
dist: precise
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova
- android list targets
- npm i
- npm install --save ./kinvey-universal-runner-1.0.0.tgz
    
before_script:
- echo no | android create avd --force -n test -t android-22 -b armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android
- cd packages/kinvey-phonegap-sdk/KinveyCordovaTestApp/
- cordova run android & adb logcat | grep chromium



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-22
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-22