os: linux
language: android
dist: precise
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0
- android list targets

install:
- npm install -g cordova@7.1.0
    
before_script:
- echo no | android create avd --force -n test -t android-24 -b armeabi-v7a
- emulator -avd test -no-window &
- android-wait-for-emulator

script:
- npm install && node ./test/platform-config --platform phonegap --os android



android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - tools
     - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

