env:
  global:
    - INTEGRATION_TESTS_NODEJS_VERSION='8.1.0'
    - INTEGRATION_TESTS_NATIVESCRIPT_VERSION='3.4.2'
    - INTEGRATION_TESTS_CORDOVA_VERSION='8.0.0'
    - UNIT_TESTS_NODEJS_VERSION='9'
    - RUN_INTEGRATION_TESTS_FILE = 'aaa'
  matrix:
    - USE_NETWORK='bbbbbbbbbbbbbb'

matrix:
  include:
    - os: linux
      env: Platform='Unit Tests'
      language: node_js
      node_js: ${UNIT_TESTS_NODEJS_VERSION}
      script: 
        - npm run test


    - os: linux
      if: type IN (pull_request)
      env: Platform='HTML5'
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      sudo: enabled
      script: 
        - node ${RUN_INTEGRATION_TESTS_FILE} --platform html5


    - os: linux
      if: type IN (pull_request)
      env: Platform='NativeScript Android'
      language: android
      jdk: oraclejdk8
      before_install: nvm install ${INTEGRATION_TESTS_NODEJS_VERSION}
      install:
        - echo no | npm i -g nativescript@${INTEGRATION_TESTS_NATIVESCRIPT_VERSION}
        - npm i
      before_script:
        - echo no | android create avd --force -n test -t android-24 -b armeabi-v7a
        - emulator -avd test -no-window &
        - android-wait-for-emulator
      script:
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform nativescript --os android


    - os: osx
      if: type IN (pull_request)
      env: Platform='NativeScript iOS'
      osx_image: xcode8.3
      language: node_js 
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      jdk: oraclejdk8
      install:
        - echo no | npm i -g nativescript@${INTEGRATION_TESTS_NATIVESCRIPT_VERSION}
        - tns usage-reporting disable
        - tns error-reporting disable
        - npm i
      before_script:
        - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
      script:
        - echo no | tns device ios
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform nativescript --os ios


    - os: osx
      if: type IN (pull_request)
      env: Platform='PhoneGap iOS'
      osx_image: xcode9.2
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      jdk: oraclejdk8
      install:
        - npm i -g cordova@${INTEGRATION_TESTS_CORDOVA_VERSION}
        - npm i
      script:
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform phonegap --os ios


    - stage: deploy
      script: skip
      language: node_js
      node_js: ${UNIT_TESTS_NODEJS_VERSION}
      deploy:
        provider: script
        script: echo ${USE_NETWORK} && echo ${CAMPFIRE_TOKEN}
        skip_cleanup: true
        on:
          all_branches: true 
   

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-24


notifications:
  email:
    - ceco19800@gmail.com