os: osx
env: 
- Xcode="8.3"
osx_image: xcode8.3
language: node_js 
node_js: "8.1.0"
jdk: oraclejdk8

install:
- npm install -g cordova
- npm i
- npm install --save ./kinvey-universal-runner-1.0.0.tgz


script:
- node ./test/platform-config --platform phonegap --os ios