os: osx
env: 
- Xcode="8.3"
osx_image: xcode8.3
language: node_js
node_js: "8.1.0"

install:
- npm install -g cordova
- npm i
- npm install --save ./kinvey-universal-runner-1.0.0.tgz

before_script:
- open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app

script:
- node ./test/platform-config --platform phonegap --os ios