os: linux
language: android
dist: trusty
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova
- android list targets
- npm i
    
before_script:
- echo no | android create avd --force -n test -t android-24 -b armeabi-v7a
- emulator -avd test -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-24