matrix:
  include:
    - os: linux
      env: Platform="Unit Tests"
      language: node_js
      node_js: '9'
      script: 
        - npm run test


    - os: linux
      if: type IN (pull_request)
      env: Platform="HTML5"
      language: node_js
      node_js: '8.1.0'
      sudo: enabled
      script: 
        - npm install --save ./kinvey-universal-runner-1.0.0.tgz
        - travis_retry node ./test/integration/run-tests --platform html5



    - stage: deploy
      language: node_js
      node_js: '9'
      deploy:
        provider: script
        script: node ./test/platform-config2 --platform html5
        skip_cleanup: true
        on:
          branch: master
          tags: true
   