os: osx
env: 
- Xcode="9.2"
osx_image: xcode9.2
language: node_js 
node_js: "8.1.0"
jdk: oraclejdk8

install:
- echo no | npm install -g nativescript
- tns device
- tns usage-reporting disable
- tns error-reporting disable

script:
- npm i && node ./test/platform-config --platform nativescript --os ios
