os: osx
env: 
- Xcode="8.3"
osx_image: xcode8.3
language: node_js 
node_js: "8.1.0"
jdk: oraclejdk8

install:
- echo no | npm install -g nativescript
- echo no | tns device ios
- tns usage-reporting disable
- tns error-reporting disable

script:
- npm i && node ./test/platform-config --platform nativescript --os ios
