os: linux
language: android
dist: trusty
sudo: required
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova@6.3.0
- android list targets
- npm i
    
before_script:
- echo no | android create avd --force --name testAVD -t android-24 -b armeabi-v7a
- emulator -avd testAVD -no-window &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-24