matrix:
  include:
    - os: linux
      env: Platform="NativeScript Android"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 8.1.0
      install:
        - echo no | npm install -g nativescript
        - npm i
        - npm install --save ./kinvey-universal-runner-1.0.0.tgz
      before_script:
        - echo no | android create avd --force -n test -t android-23 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script:
        - node ./test/platform-config --platform nativescript --os android
   

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-23