matrix:
  include:
    - os: linux
      env: Platform="HTML5"
      language: node_js
      node_js: '8.1.0'
      sudo: enabled
      script: 
        - npm install --save ./kinvey-universal-runner-1.0.0.tgz
        - node ./test/platform-config --platform html5
    - os: linux
      env: Platform="HTML6"
      language: node_js
      node_js: '9'
      sudo: enabled
      script: 
        - npm install --save ./kinvey-universal-runner-1.0.0.tgz
        - node ./test/platform-config --platform html5
   

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-21