os: linux
language: android
dist: trusty
sudo: required
jdk: oraclejdk8

env: 
- Android="IntegrationTests1"
- Android="IntegrationTests2"
- Android="IntegrationTests3"
- Android="IntegrationTests4"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova@7.1.0
- android list targets
- npm i
    
before_script:
- echo no | android create avd --force --name testAVD -t android-24 -b google_apis/armeabi-v7a
- emulator -avd testAVD -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 2048 &
- adb devices
- adb wait-for-device get-serialno
- android-wait-for-emulator




script:
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-google_apis-24