os: linux
language: android
dist: trusty
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova@7.1.0
- android list targets
- npm i
    
before_script:
- echo no | android create avd --force --name testAVD --abi google_apis/x86 --package 'system-images;android-25;google_apis;x86'
- emulator -avd test -no-window &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-x86-google_apis-25