os: linux
language: android
dist: trusty
sudo: required
jdk: oraclejdk8

env: 
- Android="IntegrationTests"


before_install:
   -echo yes | sdkmanager "tools",
   -echo yes | sdkmanager "platforms;android-25",
   -echo yes | sdkmanager "platforms;android-25",
   -echo yes | sdkmanager "extras;android;m2repository",
   -echo yes | sdkmanager "extras;google;m2repository",
   -echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2",
   -echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2",
   -echo yes | sdkmanager "system-images;android-25;google_apis;armeabi-v7a",
   -echo no | avdmanager create avd -n acib -k "system-images;android-25;google_apis;armeabi-v7a" -f --abi armeabi-v7a --tag google_apis,
   -emulator -avd acib -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 &,
   -adb wait-for-device get-serialno,
   -sdkmanager --list || true


install:
- nvm install 8.1.0
- npm install -g cordova
- android list targets
- npm i
    

script:
- android-wait-for-emulator
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2