matrix:
  include:
    - os: linux
      env: Platform="Unit Tests"
      language: node_js
      node_js: '9'
      script: 
        - npm run test
    - stage: deploy
      language: node_js
      node_js: '9'
      deploy:
        provider: script
        script: npm install --save ./kinvey-universal-runner-1.0.0.tgz
        skip_cleanup: true
        on:
          all_branches: true   
   

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-24