os: osx
env: 
- Xcode="9.2"
osx_image: xcode9.2
language: node_js
node_js: "8.1.0"
jdk: oraclejdk8

install:
- npm install -g cordova@8.0.0
- npm i
- npm install --save ./kinvey-universal-runner-1.0.0.tgz


script:
- node ./test/platform-config --platform phonegap --os ios
