os: linux
language: android
dist: precise
jdk: oraclejdk8

env: 
- Android="IntegrationTests"

before_install:
- nvm install 8.1.0

install:
- npm install -g cordova
- npm i
    
before_script:
- echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator

script:
- node ./test/platform-config --platform phonegap --os android



android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-21
    


