os: osx
env: 
- Xcode="8.3"
- Xcode="8.31"
- Xcode="8.32"
- Xcode="8.33"
osx_image: xcode8.3
language: node_js 
node_js: "8.1.0"
jdk: oraclejdk8

install:
- echo no | npm install -g nativescript
- tns usage-reporting disable
- tns error-reporting disable

before_script:
- open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app

script:
- echo no | tns device ios
- npm i && node ./test/platform-config --platform nativescript --os ios