jobs:
  include:
    - stage: Unit Tests
      if: type IN (pull_request)
      - os: linux
        env: Platform="Unit Tests"
        language: node_js
        node_js: '9'
        script: 
          - npm run test